## Jekyll config
name: "queuebit's blog"
highlighter: rouge

## Prose.io config
siteurl: "http://queuebit.net"
media: "media"

## Collections config
collections:
  books:
    output: true
    permalink: /book/:title.html
